set fileencodings=utf-8,uc-jp,shift_jis
set encoding=utf-8
set ambiwidth=double
set number
set showmatch
set showcmd
set title
set cindent
set ruler
set ignorecase
set smartcase
set hlsearch
set incsearch
set showmode
set autoindent
set smartindent
set smarttab
